// Css
import "./globals.css"
// Fonts
import { fontManrope, fontMono, fontSans } from "./fonts"
// Components
import { Footer, Header, Popup } from "@/components"
// Meta Data
export const metadata = {
  title: "Best Publishing Services",
  description: "Generated by Best Publishing Services",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontMono.variable} ${fontManrope.variable} antialiased font-sans font-normal text-black scroll-smooth`}
      >
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        {/* <Popup /> */}
      </body>
    </html>
  );
}
